// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWE9_N8fHM-w8bugAu2Wvq2t2YKQ_bEiM',
    appId: '1:803299546427:web:9235b3cabc04e6dfcfd31e',
    messagingSenderId: '803299546427',
    projectId: 'micro-challenge',
    authDomain: 'micro-challenge.firebaseapp.com',
    storageBucket: 'micro-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsF4YwzMJ8udd3DPNyQotnXbEJ_edHoRs',
    appId: '1:803299546427:android:32814298c1fb25bacfd31e',
    messagingSenderId: '803299546427',
    projectId: 'micro-challenge',
    storageBucket: 'micro-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKB3GYAMKorh-XTS8TiSb-4yDx7t5zZsM',
    appId: '1:803299546427:ios:54b196dab3fee92acfd31e',
    messagingSenderId: '803299546427',
    projectId: 'micro-challenge',
    storageBucket: 'micro-challenge.appspot.com',
    iosBundleId: 'com.example.microchallenges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKB3GYAMKorh-XTS8TiSb-4yDx7t5zZsM',
    appId: '1:803299546427:ios:85be5176e9aa1429cfd31e',
    messagingSenderId: '803299546427',
    projectId: 'micro-challenge',
    storageBucket: 'micro-challenge.appspot.com',
    iosBundleId: 'com.example.microchallenges.RunnerTests',
  );
}
